export const EXPORT_COLUMN_ORDER = [
  "title",
  "reason_snippet",
  "description",
  "steps",
  "what_you_need",
  "tips_or_variations",
  "safety_or_boundaries_note",
  "min_minutes",
  "max_minutes",
  "effort_slug",
  "active",
  "cost_tier_slug",
  "coordination_level_slug",
  "presence_requirement_slug",
  "idea_format_slugs",
  "relationship_type_fit_slugs",
  "goal_slugs",
  "context_slugs",
  "idea_category_slugs",
  "time_bucket_slug",
  "surprise_style_slug",
  "energy_vibe_slug",
  "social_setting_slugs",
  "age_band_fit_slugs",
  "event_tag_slugs",
  "idea_collection_slugs",
  "cadence_tag_slugs",
  "physical_intensity_slug",
  "accessibility_flag_slugs",
  "weather_dependence_slugs",
  "gender_fit_slugs",
  "status",
  "editorial_note",
  "source",
] as const;

export type ExportColumn = (typeof EXPORT_COLUMN_ORDER)[number];

export const TRAIT_EXPORT_COLUMN_BY_TYPE: Record<string, ExportColumn> = {
  effort: "effort_slug",
  time_bucket: "time_bucket_slug",
  cost_tier: "cost_tier_slug",
  coordination_level: "coordination_level_slug",
  presence_requirement: "presence_requirement_slug",
  idea_format: "idea_format_slugs",
  person_type: "relationship_type_fit_slugs",
  goal: "goal_slugs",
  context: "context_slugs",
  idea_category: "idea_category_slugs",
  surprise_style: "surprise_style_slug",
  energy_vibe: "energy_vibe_slug",
  social_setting: "social_setting_slugs",
  age_band: "age_band_fit_slugs",
  event_tag: "event_tag_slugs",
  idea_collection: "idea_collection_slugs",
  cadence_tag: "cadence_tag_slugs",
  physical_intensity: "physical_intensity_slug",
  accessibility_flag: "accessibility_flag_slugs",
  weather_dependence: "weather_dependence_slugs",
  person_gender: "gender_fit_slugs",
};

export const MULTI_TRAIT_TYPES = new Set<string>([
  "idea_format",
  "person_type",
  "goal",
  "context",
  "idea_category",
  "social_setting",
  "age_band",
  "event_tag",
  "idea_collection",
  "cadence_tag",
  "accessibility_flag",
  "weather_dependence",
  "person_gender",
]);
